include:
  - 'https://colisweb-idl.gitlab.io/colisweb-open-source/ci-common/v17.3.3/templates/scala.yml'

compile gdrive-scala-client:
  extends: .sbt-compile-cross

format:
  extends: .sbt-format

test google-drive-scala-client:
  extends:
  - .sbt-test
  - .rules-only-for-master
  script:
    - gpg -q --decrypt core/src/test/resources/google-credentials.json.secret > core/src/test/resources/google-credentials.json
    - gpg -q --decrypt core/src/test/resources/big-query-data-source-config.json.secret > core/src/test/resources/big-query-data-source-config.json
    - sbt +test

unused-dependencies:
  extends: .sbt-unused-dependencies

version:
  extends: .version

publish on sonatype:
  extends: .sonatype-publish
